export const SET_CURRENT_USER = 'SET_CURRENT_USER';


export const TOGGLE_CART_VISIBILITY = 'TOGGLE_CART_VISIBILITY';
export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const REMOVE_CHECKOUT_ITEM = 'REMOVE_CHECKOUT_ITEM';